
void CubeUpdate(int layerno){ 
  
  if(layerno == 1){                 
                                  // Tlc.set(OUTPUT, BRIGHTNESS VALUE (0-4095)), general use of Tlc.set      
    Tlc.set(AchR, AaR);             // set AaR brightness to AchR OUTPUT(OUTPUT 0); first TLC5940 
    Tlc.set(BchR, BaR);             // set BaR brightness to BchR OUTPUT(OUTPUT 1);
    Tlc.set(CchR, CaR);             // set CaR brightness to CchR OUTPUT(OUTPUT 2);
    Tlc.set(DchR, DaR);             // set DaR brightness to DchR OUTPUT(OUTPUT 3);
    Tlc.set(EchR, EaR);             // set EaR brightness to EchR OUTPUT(OUTPUT 4);
    Tlc.set(FchR, FaR);             // set FaR brightness to FchR OUTPUT(OUTPUT 5);
    Tlc.set(GchR, GaR);             // set GaR brightness to GchR OUTPUT(OUTPUT 6);
    Tlc.set(HchR, HaR);             // set HaR brightness to HchR OUTPUT(OUTPUT 7);
    Tlc.set(IchR, IaR);             // set IaR brightness to IchR OUTPUT(OUTPUT 8);
    Tlc.set(JchR, JaR);             // set JaR brightness to JchR OUTPUT(OUTPUT 9);
    Tlc.set(KchR, KaR);             // set KaR brightness to KchR OUTPUT(OUTPUT 10);
    Tlc.set(LchR, LaR);             // set LaR brightness to LchR OUTPUT(OUTPUT 11);
    Tlc.set(MchR, MaR);             // set MaR brightness to MchR OUTPUT(OUTPUT 12);
    Tlc.set(NchR, NaR);             // set NaR brightness to NchR OUTPUT(OUTPUT 13);
    Tlc.set(OchR, OaR);             // set OaR brightness to OchR OUTPUT(OUTPUT 14);
    Tlc.set(PchR, PaR);             // set PaR brightness to PchR OUTPUT(OUTPUT 15);
    Tlc.set(AchG, AaG);             // set AaG brightness to AchG OUTPUT(OUTPUT 0); second TLC5940
    Tlc.set(BchG, BaG);             // set BaG brightness to BchG OUTPUT(OUTPUT 1);
    Tlc.set(CchG, CaG);             // set CaG brightness to CchG OUTPUT(OUTPUT 2);
    Tlc.set(DchG, DaG);             // set DaG brightness to DchG OUTPUT(OUTPUT 3);
    Tlc.set(EchG, EaG);             // set EaG brightness to EchG OUTPUT(OUTPUT 4);
    Tlc.set(FchG, FaG);             // set FaG brightness to FchG OUTPUT(OUTPUT 5);
    Tlc.set(GchG, GaG);             // set GaG brightness to GchG OUTPUT(OUTPUT 6);
    Tlc.set(HchG, HaG);             // set HaG brightness to HchG OUTPUT(OUTPUT 7);
    Tlc.set(IchG, IaG);             // set IaG brightness to IchG OUTPUT(OUTPUT 8);
    Tlc.set(JchG, JaG);             // set JaG brightness to JchG OUTPUT(OUTPUT 9);
    Tlc.set(KchG, KaG);             // set KaG brightness to KchG OUTPUT(OUTPUT 10);
    Tlc.set(LchG, LaG);             // set LaG brightness to LchG OUTPUT(OUTPUT 11);
    Tlc.set(MchG, MaG);             // set MaG brightness to MchG OUTPUT(OUTPUT 12);
    Tlc.set(NchG, NaG);             // set NaG brightness to NchG OUTPUT(OUTPUT 13);
    Tlc.set(OchG, OaG);             // set OaG brightness to OchG OUTPUT(OUTPUT 14);
    Tlc.set(PchG, PaG);             // set PaG brightness to PchG OUTPUT(OUTPUT 15);
    Tlc.set(AchB, AaB);             // set AaB brightness to AchB OUTPUT(OUTPUT 0); third TLC5940
    Tlc.set(BchB, BaB);             // set BaB brightness to BchB OUTPUT(OUTPUT 1);
    Tlc.set(CchB, CaB);             // set CaB brightness to CchB OUTPUT(OUTPUT 2);
    Tlc.set(DchB, DaB);             // set DaB brightness to DchB OUTPUT(OUTPUT 3);
    Tlc.set(EchB, EaB);             // set EaB brightness to EchB OUTPUT(OUTPUT 4);
    Tlc.set(FchB, FaB);             // set FaB brightness to FchB OUTPUT(OUTPUT 5);
    Tlc.set(GchB, GaB);             // set GaB brightness to GchB OUTPUT(OUTPUT 6);
    Tlc.set(HchB, HaB);             // set HaB brightness to HchB OUTPUT(OUTPUT 7);
    Tlc.set(IchB, IaB);             // set IaB brightness to IchB OUTPUT(OUTPUT 8);
    Tlc.set(JchB, JaB);             // set JaB brightness to JchB OUTPUT(OUTPUT 9);
    Tlc.set(KchB, KaB);             // set KaB brightness to KchB OUTPUT(OUTPUT 10);
    Tlc.set(LchB, LaB);             // set LaB brightness to LchB OUTPUT(OUTPUT 11);
    Tlc.set(MchB, MaB);             // set MaB brightness to MchB OUTPUT(OUTPUT 12);
    Tlc.set(NchB, NaB);             // set NaB brightness to NchB OUTPUT(OUTPUT 13);
    Tlc.set(OchB, OaB);             // set OaB brightness to OchB OUTPUT(OUTPUT 14);
    Tlc.set(PchB, PaB);             // set PaB brightness to PchB OUTPUT(OUTPUT 15);
    
    digitalWrite(LayerOne, HIGH);   // sets LayerOne (pin A0) High (not active)--> Layer one OFF
    digitalWrite(LayerTwo, HIGH);   // sets LayerTwo (pin A1) High (not active)--> Layer two OFF
    digitalWrite(LayerThree, HIGH); // sets LayerThree (pin A2) High (not active)--> Layer three OFF
    digitalWrite(LayerFour, HIGH);  // sets LayerFour (pin A3) High (not active)--> Layer four OFF
    Tlc.update();                   // writes the values for the LEDs brightness to the tlc
    delay(0);                                // give the tlc some time to let the value settle
    digitalWrite(LayerOne, LOW);    // sets LayerOne (pin A0) Low (active)--> Layer one ON
  }
  
    if(layerno == 2){
    
  
    Tlc.set(AchR, AbR);             // same as if(layerno == 1) but we use different brightness, so we define LEDs in the second layer
    Tlc.set(BchR, BbR);
    Tlc.set(CchR, CbR);
    Tlc.set(DchR, DbR);    
    Tlc.set(EchR, EbR);
    Tlc.set(FchR, FbR);
    Tlc.set(GchR, GbR);
    Tlc.set(HchR, HbR);    
    Tlc.set(IchR, IbR);
    Tlc.set(JchR, JbR);
    Tlc.set(KchR, KbR);
    Tlc.set(LchR, LbR);
    Tlc.set(MchR, MbR);
    Tlc.set(NchR, NbR);
    Tlc.set(OchR, ObR);
    Tlc.set(PchR, PbR);
    Tlc.set(AchG, AbG);            
    Tlc.set(BchG, BbG);
    Tlc.set(CchG, CbG);
    Tlc.set(DchG, DbG);    
    Tlc.set(EchG, EbG);
    Tlc.set(FchG, FbG);
    Tlc.set(GchG, GbG);
    Tlc.set(HchG, HbG);    
    Tlc.set(IchG, IbG);
    Tlc.set(JchG, JbG);
    Tlc.set(KchG, KbG);
    Tlc.set(LchG, LbG);
    Tlc.set(MchG, MbG);
    Tlc.set(NchG, NbG);
    Tlc.set(OchG, ObG);
    Tlc.set(PchG, PbG);
    Tlc.set(AchB, AbB);             
    Tlc.set(BchB, BbB);
    Tlc.set(CchB, CbB);
    Tlc.set(DchB, DbB);    
    Tlc.set(EchB, EbB);
    Tlc.set(FchB, FbB);
    Tlc.set(GchB, GbB);
    Tlc.set(HchB, HbB);    
    Tlc.set(IchB, IbB);
    Tlc.set(JchB, JbB);
    Tlc.set(KchB, KbB);
    Tlc.set(LchB, LbB);
    Tlc.set(MchB, MbB);
    Tlc.set(NchB, NbB);
    Tlc.set(OchB, ObB);
    Tlc.set(PchB, PbB);
    
    digitalWrite(LayerOne, HIGH);  // same as if(layerno==1)
    digitalWrite(LayerTwo, HIGH);
    digitalWrite(LayerThree, HIGH);
    digitalWrite(LayerFour, HIGH);
    Tlc.update();
    delay(0);
    digitalWrite(LayerTwo, LOW);  // sets LayerTwo (pin A1) Low (active)--> Layer two ON
  }
  
  
  if(layerno == 3){
    
    Tlc.set(AchR, AcR);          // same as if(layerno == 1) but we use different brightness, so we define LEDs in the 3. layer
    Tlc.set(BchR, BcR);
    Tlc.set(CchR, CcR);
    Tlc.set(DchR, DcR);    
    Tlc.set(EchR, EcR);
    Tlc.set(FchR, FcR);
    Tlc.set(GchR, GcR);
    Tlc.set(HchR, HcR);    
    Tlc.set(IchR, IcR);
    Tlc.set(JchR, JcR);
    Tlc.set(KchR, KcR);
    Tlc.set(LchR, LcR);
    Tlc.set(MchR, McR);
    Tlc.set(NchR, NcR);
    Tlc.set(OchR, OcR);
    Tlc.set(PchR, PcR);
    Tlc.set(AchG, AcG);         
    Tlc.set(BchG, BcG);
    Tlc.set(CchG, CcG);
    Tlc.set(DchG, DcG);    
    Tlc.set(EchG, EcG);
    Tlc.set(FchG, FcG);
    Tlc.set(GchG, GcG);
    Tlc.set(HchG, HcG);    
    Tlc.set(IchG, IcG);
    Tlc.set(JchG, JcG);
    Tlc.set(KchG, KcG);
    Tlc.set(LchG, LcG);
    Tlc.set(MchG, McG);
    Tlc.set(NchG, NcG);
    Tlc.set(OchG, OcG);
    Tlc.set(PchG, PcG);
    Tlc.set(AchB, AcB);          
    Tlc.set(BchB, BcB);
    Tlc.set(CchB, CcB);
    Tlc.set(DchB, DcB);    
    Tlc.set(EchB, EcB);
    Tlc.set(FchB, FcB);
    Tlc.set(GchB, GcB);
    Tlc.set(HchB, HcB);    
    Tlc.set(IchB, IcB);
    Tlc.set(JchB, JcB);
    Tlc.set(KchB, KcB);
    Tlc.set(LchB, LcB);
    Tlc.set(MchB, McB);
    Tlc.set(NchB, NcB);
    Tlc.set(OchB, OcB);
    Tlc.set(PchB, PcB);
    
    digitalWrite(LayerOne, HIGH);   // same as if(layerno==1)
    digitalWrite(LayerTwo, HIGH);
    digitalWrite(LayerThree, HIGH);
    digitalWrite(LayerFour, HIGH);
    Tlc.update();
    delay(0);
    digitalWrite(LayerThree, LOW);   // sets LayerThree (pin A2) Low (active)--> Layer three ON 
  }
  
  
  if(layerno == 4){
    
    Tlc.set(AchR, AdR);              // same as if(layerno == 1) but we use different brightness, so we define LEDs in the 4. layer
    Tlc.set(BchR, BdR);
    Tlc.set(CchR, CdR);
    Tlc.set(DchR, DdR);    
    Tlc.set(EchR, EdR);
    Tlc.set(FchR, FdR);
    Tlc.set(GchR, GdR);
    Tlc.set(HchR, HdR);    
    Tlc.set(IchR, IdR);
    Tlc.set(JchR, JdR);
    Tlc.set(KchR, KdR);
    Tlc.set(LchR, LdR);
    Tlc.set(MchR, MdR);
    Tlc.set(NchR, NdR);
    Tlc.set(OchR, OdR);
    Tlc.set(PchR, PdR);
    Tlc.set(AchG, AdG);             
    Tlc.set(BchG, BdG);
    Tlc.set(CchG, CdG);
    Tlc.set(DchG, DdG);    
    Tlc.set(EchG, EdG);
    Tlc.set(FchG, FdG);
    Tlc.set(GchG, GdG);
    Tlc.set(HchG, HdG);    
    Tlc.set(IchG, IdG);
    Tlc.set(JchG, JdG);
    Tlc.set(KchG, KdG);
    Tlc.set(LchG, LdG);
    Tlc.set(MchG, MdG);
    Tlc.set(NchG, NdG);
    Tlc.set(OchG, OdG);
    Tlc.set(PchG, PdG);
    Tlc.set(AchB, AdB);             
    Tlc.set(BchB, BdB);
    Tlc.set(CchB, CdB);
    Tlc.set(DchB, DdB);    
    Tlc.set(EchB, EdB);
    Tlc.set(FchB, FdB);
    Tlc.set(GchB, GdB);
    Tlc.set(HchB, HdB);    
    Tlc.set(IchB, IdB);
    Tlc.set(JchB, JdB);
    Tlc.set(KchB, KdB);
    Tlc.set(LchB, LdB);
    Tlc.set(MchB, MdB);
    Tlc.set(NchB, NdB);
    Tlc.set(OchB, OdB);
    Tlc.set(PchB, PdB);
    
    digitalWrite(LayerOne, HIGH);  // same as if(layerno==1)
    digitalWrite(LayerTwo, HIGH);
    digitalWrite(LayerThree, HIGH);
    digitalWrite(LayerFour, HIGH);
    Tlc.update();
    delay(0);
    digitalWrite(LayerFour, LOW);  // sets LayerFour (pin A3) Low (active)--> Layer four ON
  }}
      
  void reset(){                 // we set all LEDs to 0 brightness
  AaR = 0;
  BaR = 0;
  CaR = 0;
  DaR = 0;
  EaR = 0;
  FaR = 0;
  GaR = 0;
  HaR = 0;
  IaR = 0;
  JaR = 0;
  KaR = 0;
  LaR = 0;
  MaR = 0;
  NaR = 0;
  OaR = 0;
  PaR = 0;
  AaG = 0;
  BaG = 0;
  CaG = 0;
  DaG = 0;
  EaG = 0;
  FaG = 0;
  GaG = 0;
  HaG = 0;
  IaG = 0;
  JaG = 0;
  KaG = 0;
  LaG = 0;
  MaG = 0;
  NaG = 0;
  OaG = 0;
  PaG = 0;
  AaB = 0;
  BaB = 0;
  CaB = 0;
  DaB = 0;
  EaB = 0;
  FaB = 0;
  GaB = 0;
  HaB = 0;
  IaB = 0;
  JaB = 0;
  KaB = 0;
  LaB = 0;
  MaB = 0;
  NaB = 0;
  OaB = 0;
  PaB = 0;

  AbR = 0;
  BbR = 0;
  CbR = 0;
  DbR = 0;
  EbR = 0;
  FbR = 0;
  GbR = 0;
  HbR = 0;
  IbR = 0;
  JbR = 0;
  KbR = 0;
  LbR = 0;
  MbR = 0;
  NbR = 0;
  ObR = 0;
  PbR = 0;
  AbG = 0;
  BbG = 0;
  CbG = 0;
  DbG = 0;
  EbG = 0;
  FbG = 0;
  GbG = 0;
  HbG = 0;
  IbG = 0;
  JbG = 0;
  KbG = 0;
  LbG = 0;
  MbG = 0;
  NbG = 0;
  ObG = 0;
  PbG = 0;
  AbB = 0;
  BbB = 0;
  CbB = 0;
  DbB = 0;
  EbB = 0;
  FbB = 0;
  GbB = 0;
  HbB = 0;
  IbB = 0;
  JbB = 0;
  KbB = 0;
  LbB = 0;
  MbB = 0;
  NbB = 0;
  ObB = 0;
  PbB = 0;

  AcR = 0;
  BcR = 0;
  CcR = 0;
  DcR = 0;
  EcR = 0;
  FcR = 0;
  GcR = 0;
  HcR = 0;
  IcR = 0;
  JcR = 0;
  KcR = 0;
  LcR = 0;
  McR = 0;
  NcR = 0;
  OcR = 0;
  PcR = 0;
  AcG = 0;
  BcG = 0;
  CcG = 0;
  DcG = 0;
  EcG = 0;
  FcG = 0;
  GcG = 0;
  HcG = 0;
  IcG = 0;
  JcG = 0;
  KcG = 0;
  LcG = 0;
  McG = 0;
  NcG = 0;
  OcG = 0;
  PcG = 0;
  AcB = 0;
  BcB = 0;
  CcB = 0;
  DcB = 0;
  EcB = 0;
  FcB = 0;
  GcB = 0;
  HcB = 0;
  IcB = 0;
  JcB = 0;
  KcB = 0;
  LcB = 0;
  McB = 0;
  NcB = 0;
  OcB = 0;
  PcB = 0;
 

  AdR = 0;
  BdR = 0;
  CdR = 0;
  DdR = 0;
  EdR = 0;
  FdR = 0;
  GdR = 0;
  HdR = 0;
  IdR = 0;
  JdR = 0;
  KdR = 0;
  LdR = 0;
  MdR = 0;
  NdR = 0;
  OdR = 0;
  PdR = 0;
  AdG = 0;
  BdG = 0;
  CdG = 0;
  DdG = 0;
  EdG = 0;
  FdG = 0;
  GdG = 0;
  HdG = 0;
  IdG = 0;
  JdG = 0;
  KdG = 0;
  LdG = 0;
  MdG = 0;
  NdG = 0;
  OdG = 0;
  PdG = 0;
  AdB = 0;
  BdB = 0;
  CdB = 0;
  DdB = 0;
  EdB = 0;
  FdB = 0;
  GdB = 0;
  HdB = 0;
  IdB = 0;
  JdB = 0;
  KdB = 0;
  LdB = 0;
  MdB = 0;
  NdB = 0;
  OdB = 0;
  PdB = 0;}
  
  void allred(){
  AaR = bright;
  BaR = bright;
  CaR = bright;
  DaR = bright;
  EaR = bright;
  FaR = bright;
  GaR = bright;
  HaR = bright;
  IaR = bright;
  JaR = bright;
  KaR = bright;
  LaR = bright;
  MaR = bright;
  NaR = bright;
  OaR = bright;
  PaR = bright;
  AbR = bright;
  BbR = bright;
  CbR = bright;
  DbR = bright;
  EbR = bright;
  FbR = bright;
  GbR = bright;
  HbR = bright;
  IbR = bright;
  JbR = bright;
  KbR = bright;
  LbR = bright;
  MbR = bright;
  NbR = bright;
  ObR = bright;
  PbR = bright;
  AcR = bright;
  BcR = bright;
  CcR = bright;
  DcR = bright;
  EcR = bright;
  FcR = bright;
  GcR = bright;
  HcR = bright;
  IcR = bright;
  JcR = bright;
  KcR = bright;
  LcR = bright;
  McR = bright;
  NcR = bright;
  OcR = bright;
  PcR = bright;
  AdR = bright;
  BdR = bright;
  CdR = bright;
  DdR = bright;
  EdR = bright;
  FdR = bright;
  GdR = bright;
  HdR = bright;
  IdR = bright;
  JdR = bright;
  KdR = bright;
  LdR = bright;
  MdR = bright;
  NdR = bright;
  OdR = bright;
  PdR = bright;}
  
  void allgreen(){
  AaG = bright;
  BaG = bright;
  CaG = bright;
  DaG = bright;
  EaG = bright;
  FaG = bright;
  GaG = bright;
  HaG = bright;
  IaG = bright;
  JaG = bright;
  KaG = bright;
  LaG = bright;
  MaG = bright;
  NaG = bright;
  OaG = bright;
  PaG = bright;
  AbG = bright;
  BbG = bright;
  CbG = bright;
  DbG = bright;
  EbG = bright;
  FbG = bright;
  GbG = bright;
  HbG = bright;
  IbG = bright;
  JbG = bright;
  KbG = bright;
  LbG = bright;
  MbG = bright;
  NbG = bright;
  ObG = bright;
  PbG = bright;
  AcG = bright;
  BcG = bright;
  CcG = bright;
  DcG = bright;
  EcG = bright;
  FcG = bright;
  GcG = bright;
  HcG = bright;
  IcG = bright;
  JcG = bright;
  KcG = bright;
  LcG = bright;
  McG = bright;
  NcG = bright;
  OcG = bright;
  PcG = bright;
  AdG = bright;
  BdG = bright;
  CdG = bright;
  DdG = bright;
  EdG = bright;
  FdG = bright;
  GdG = bright;
  HdG = bright;
  IdG = bright;
  JdG = bright;
  KdG = bright;
  LdG = bright;
  MdG = bright;
  NdG = bright;
  OdG = bright;
  PdG = bright;}
  
  void allblue(){
  AaB = bright;
  BaB = bright;
  CaB = bright;
  DaB = bright;
  EaB = bright;
  FaB = bright;
  GaB = bright;
  HaB = bright;
  IaB = bright;
  JaB = bright;
  KaB = bright;
  LaB = bright;
  MaB = bright;
  NaB = bright;
  OaB = bright;
  PaB = bright;
  AbB = bright;
  BbB = bright;
  CbB = bright;
  DbB = bright;
  EbB = bright;
  FbB = bright;
  GbB = bright;
  HbB = bright;
  IbB = bright;
  JbB = bright;
  KbB = bright;
  LbB = bright;
  MbB = bright;
  NbB = bright;
  ObB = bright;
  PbB = bright;
  AcB = bright;
  BcB = bright;
  CcB = bright;
  DcB = bright;
  EcB = bright;
  FcB = bright;
  GcB = bright;
  HcB = bright;
  IcB = bright;
  JcB = bright;
  KcB = bright;
  LcB = bright;
  McB = bright;
  NcB = bright;
  OcB = bright;
  PcB = bright;
  AdB = bright;
  BdB = bright;
  CdB = bright;
  DdB = bright;
  EdB = bright;
  FdB = bright;
  GdB = bright;
  HdB = bright;
  IdB = bright;
  JdB = bright;
  KdB = bright;
  LdB = bright;
  MdB = bright;
  NdB = bright;
  OdB = bright;
  PdB = bright;}
  
  
